name: Bazel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs: # https://github.com/marketplace/actions/bazel-action
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Test
      run: |
        make test BAZEL="${GITHUB_WORKSPACE}/bin/bazel"

    - name: Build
      run: |
        make build BAZEL="${GITHUB_WORKSPACE}/bin/bazel"

    - name: Run
      run: |
        make run BAZEL="${GITHUB_WORKSPACE}/bin/bazel"
